# Uncomment the next line to define a global platform for your project
 platform :ios, '14.0'
use_frameworks!
install! 'cocoapods', :deterministic_uuids => false
target 'WitVPN' do
# Pods for WitVPN
pod 'Google-Mobile-Ads-SDK', '~> 10.1.0'
pod 'PromiseKit'
pod 'DeviceKit', '~> 5.2'
pod 'GBDeviceInfo'
pod 'lottie-ios'
pod 'PureLayout'
pod 'SwiftyStoreKit'
pod 'SwiftDate'
pod 'SideMenu'
pod 'Macaw'
pod 'Localize-Swift'
pod 'SVProgressHUD'
pod 'TTTAttributedLabel'
pod 'SVPullToRefresh'

# Pods for Firebase
pod 'Firebase', '10.24.0'
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Crashlytics'
pod 'Firebase/Firestore'
end

target 'PacketTunnelProvider' do
  pod 'OpenVPNAdapter', :git => 'https://github.com/ss-abramchuk/OpenVPNAdapter.git', :tag => '0.8.0'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
   config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
   config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
   config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
   config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
   xcconfig_path = config.base_configuration_reference.real_path
   xcconfig = File.read(xcconfig_path)
   xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
   File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
  end
 end
end
